SSH_TUNNEL_MACHINE:
  ip: "192.168.15.42"
  port: 3300
  username: "slview"
  password: "slview"

SONAR_SERVER:
  ip: "10.220.97.96"
  port: 9000
  username: "zy-zhangnt"
  password: "uTh^z*ewDL*kxR!V"

LOCAL_SERVER:
  ip: "127.0.0.1"
  port: 9000

PROJECT_INFO:
  key: "cnv-front-schedule-java-service-develop"
  token: "0d4784d7430dae414d7b9365149285f29150d9ca"
  local_path: "D:\\ideaCode\\company\\gitCode\\sonarCode\\cnv-front-schedule-java-service"
  language: "Java 8"
  test_framework: "junit4"

ZHIPU:
  url: "https://open.bigmodel.cn/api/paas/v4/chat/completions"
#  token: "ea0ab6b243bfec4f56d9f8d880780a44.nttX3gepmAC3ZTSn"
  token: "4da188ece32381d716e1b33c9c0b3e87.x0a5qkTcxHTbK1mK"
  model1: "glm-4-plus"
  model2: "glm-4-air"
